#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := task-3-can-bus-iot-device_fw
PROJECT_VER  := v1.0.0

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/sys/

include $(IDF_PATH)/make/project.mk

